/**
 * Chrome "Customise Chrome" theme presets.
 *
 * Seed colors and variants from Chromium source:
 *   chrome/browser/ui/webui/cr_components/theme_color_picker/customize_chrome_colors.cc
 *
 * Light/dark palettes derived using Material Design 3 TonalSpot/Neutral
 * algorithms in OKLCH color space.
 */

export interface ThemeColors {
  surfaceContainer: string;
  surface: string;
  surfaceContainerHigh: string;
  primary: string;
  onPrimary: string;
  primaryHover: string;
  onSurface: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  border: string;
}

export interface ThemePreset {
  name: string;
  swatchLight: string;
  swatchDark: string;
  light: ThemeColors;
  dark: ThemeColors;
}

export const themePresets: Record<string, ThemePreset> = {
  default: {
    name: "Default",
    swatchLight: "#dadce0",
    swatchDark: "#35363a",
    light: {
      surfaceContainer: "#f1f3f4",
      surface: "#ffffff",
      surfaceContainerHigh: "#e8eaed",
      primary: "#1a73e8",
      onPrimary: "#ffffff",
      primaryHover: "#1557b0",
      onSurface: "#202124",
      onSurfaceVariant: "#5f6368",
      outline: "#80868b",
      outlineVariant: "#9aa0a6",
      border: "#dadce0",
    },
    dark: {
      surfaceContainer: "#292a2d",
      surface: "#35363a",
      surfaceContainerHigh: "#3c4043",
      primary: "#8ab4f8",
      onPrimary: "#000000",
      primaryHover: "#669df6",
      onSurface: "#e8eaed",
      onSurfaceVariant: "#bdc1c6",
      outline: "#9aa0a6",
      outlineVariant: "#80868b",
      border: "#3c4043",
    },
  },
  blue: {
    name: "Blue",
    swatchLight: "#d0dff9",
    swatchDark: "#113f9c",
    light: {
      surfaceContainer: "#f5f9fe",
      surface: "#ecf2fd",
      surfaceContainerHigh: "#e4ecf9",
      primary: "#113f9c",
      onPrimary: "#ffffff",
      primaryHover: "#082769",
      onSurface: "#010309",
      onSurfaceVariant: "#232e42",
      outline: "#3c485e",
      outlineVariant: "#57647b",
      border: "#b0bed8",
    },
    dark: {
      surfaceContainer: "#0b0f18",
      surface: "#11161f",
      surfaceContainerHigh: "#1c222b",
      primary: "#a2bef2",
      onPrimary: "#000000",
      primaryHover: "#759ee9",
      onSurface: "#d7deec",
      onSurfaceVariant: "#b0bed8",
      outline: "#919fb8",
      outlineVariant: "#738199",
      border: "#232e42",
    },
  },
  "cool-grey": {
    name: "Cool Grey",
    swatchLight: "#d0dff9",
    swatchDark: "#364868",
    light: {
      surfaceContainer: "#f5f9fe",
      surface: "#ecf2fc",
      surfaceContainerHigh: "#e6ebf6",
      primary: "#364868",
      onPrimary: "#ffffff",
      primaryHover: "#1d2d4c",
      onSurface: "#020307",
      onSurfaceVariant: "#282e38",
      outline: "#424853",
      outlineVariant: "#5d646f",
      border: "#b7becb",
    },
    dark: {
      surfaceContainer: "#0c0f16",
      surface: "#12161d",
      surfaceContainerHigh: "#1e2229",
      primary: "#a9bee5",
      onPrimary: "#000000",
      primaryHover: "#8a9fc4",
      onSurface: "#d9dee8",
      onSurfaceVariant: "#b7becb",
      outline: "#989fab",
      outlineVariant: "#7a818d",
      border: "#282e38",
    },
  },
  grey: {
    name: "Grey",
    swatchLight: "#e8ddc1",
    swatchDark: "#54461e",
    light: {
      surfaceContainer: "#faf8f2",
      surface: "#f6f2e7",
      surfaceContainerHigh: "#efebe0",
      primary: "#54461e",
      onPrimary: "#ffffff",
      primaryHover: "#3a2c01",
      onSurface: "#050301",
      onSurfaceVariant: "#322d22",
      outline: "#4c473c",
      outlineVariant: "#686357",
      border: "#c3bdb0",
    },
    dark: {
      surfaceContainer: "#120f08",
      surface: "#19160e",
      surfaceContainerHigh: "#242119",
      primary: "#cdbd92",
      onPrimary: "#000000",
      primaryHover: "#ad9d74",
      onSurface: "#e2ded3",
      onSurfaceVariant: "#c3bdb0",
      outline: "#a39e91",
      outlineVariant: "#858073",
      border: "#322d22",
    },
  },
  aqua: {
    name: "Aqua",
    swatchLight: "#c2e7e1",
    swatchDark: "#005f54",
    light: {
      surfaceContainer: "#f3faf9",
      surface: "#e7f6f3",
      surfaceContainerHigh: "#ddf0ed",
      primary: "#005f54",
      onPrimary: "#ffffff",
      primaryHover: "#003e36",
      onSurface: "#000504",
      onSurfaceVariant: "#123431",
      outline: "#2d4f4b",
      outlineVariant: "#496b66",
      border: "#a2c7c1",
    },
    dark: {
      surfaceContainer: "#051211",
      surface: "#0b1917",
      surfaceContainerHigh: "#162523",
      primary: "#7fcfc5",
      onPrimary: "#000000",
      primaryHover: "#16b6a9",
      onSurface: "#d0e3e0",
      onSurfaceVariant: "#a2c7c1",
      outline: "#83a7a2",
      outlineVariant: "#658883",
      border: "#123431",
    },
  },
  green: {
    name: "Green",
    swatchLight: "#cfe5cd",
    swatchDark: "#005b00",
    light: {
      surfaceContainer: "#f5faf5",
      surface: "#ecf5eb",
      surfaceContainerHigh: "#e4efe3",
      primary: "#005b00",
      onPrimary: "#ffffff",
      primaryHover: "#003b00",
      onSurface: "#010401",
      onSurfaceVariant: "#223320",
      outline: "#3b4d39",
      outlineVariant: "#566954",
      border: "#b0c5ad",
    },
    dark: {
      surfaceContainer: "#0a120a",
      surface: "#111810",
      surfaceContainerHigh: "#1c241b",
      primary: "#a0cb9c",
      onPrimary: "#000000",
      primaryHover: "#70b16b",
      onSurface: "#d7e2d6",
      onSurfaceVariant: "#b0c5ad",
      outline: "#91a58e",
      outlineVariant: "#738771",
      border: "#223320",
    },
  },
  viridian: {
    name: "Viridian",
    swatchLight: "#d0e5cd",
    swatchDark: "#355031",
    light: {
      surfaceContainer: "#f5faf5",
      surface: "#ecf5eb",
      surfaceContainerHigh: "#e6eee5",
      primary: "#355031",
      onPrimary: "#ffffff",
      primaryHover: "#1b3518",
      onSurface: "#020402",
      onSurfaceVariant: "#283027",
      outline: "#424b41",
      outlineVariant: "#5d665c",
      border: "#b7c1b5",
    },
    dark: {
      surfaceContainer: "#0c110b",
      surface: "#121812",
      surfaceContainerHigh: "#1e241d",
      primary: "#a8c8a4",
      onPrimary: "#000000",
      primaryHover: "#8aa886",
      onSurface: "#d9e1d8",
      onSurfaceVariant: "#b7c1b5",
      outline: "#98a296",
      outlineVariant: "#7a8378",
      border: "#283027",
    },
  },
  citron: {
    name: "Citron",
    swatchLight: "#e6dec1",
    swatchDark: "#624200",
    light: {
      surfaceContainer: "#faf8f3",
      surface: "#f5f2e6",
      surfaceContainerHigh: "#efebdd",
      primary: "#624200",
      onPrimary: "#ffffff",
      primaryHover: "#412a00",
      onSurface: "#050300",
      onSurfaceVariant: "#342e15",
      outline: "#4e482f",
      outlineVariant: "#6a6349",
      border: "#c5bea1",
    },
    dark: {
      surfaceContainer: "#120f06",
      surface: "#19160b",
      surfaceContainerHigh: "#242217",
      primary: "#cdbe82",
      onPrimary: "#000000",
      primaryHover: "#b59d3a",
      onSurface: "#e2ded0",
      onSurfaceVariant: "#c5bea1",
      outline: "#a69f83",
      outlineVariant: "#878065",
      border: "#342e15",
    },
  },
  orange: {
    name: "Orange",
    swatchLight: "#f4d7c6",
    swatchDark: "#841e00",
    light: {
      surfaceContainer: "#fdf7f4",
      surface: "#fbefe8",
      surfaceContainerHigh: "#f7e8df",
      primary: "#841e00",
      onPrimary: "#ffffff",
      primaryHover: "#581100",
      onSurface: "#070201",
      onSurfaceVariant: "#3e281a",
      outline: "#594233",
      outlineVariant: "#765d4e",
      border: "#d3b7a6",
    },
    dark: {
      surfaceContainer: "#160d07",
      surface: "#1d140d",
      surfaceContainerHigh: "#2a1f19",
      primary: "#e8b08e",
      onPrimary: "#000000",
      primaryHover: "#d88853",
      onSurface: "#e9dbd2",
      onSurfaceVariant: "#d3b7a6",
      outline: "#b39888",
      outlineVariant: "#947a6a",
      border: "#3e281a",
    },
  },
  apricot: {
    name: "Apricot",
    swatchLight: "#f5d7c7",
    swatchDark: "#623e29",
    light: {
      surfaceContainer: "#fdf7f4",
      surface: "#fbefe9",
      surfaceContainerHigh: "#f4e9e2",
      primary: "#623e29",
      onPrimary: "#ffffff",
      primaryHover: "#45240f",
      onSurface: "#060201",
      onSurfaceVariant: "#362b25",
      outline: "#51453e",
      outlineVariant: "#6d6059",
      border: "#c9bab2",
    },
    dark: {
      surfaceContainer: "#150e0a",
      surface: "#1c1410",
      surfaceContainerHigh: "#28201b",
      primary: "#deb39b",
      onPrimary: "#000000",
      primaryHover: "#be947d",
      onSurface: "#e7dbd5",
      onSurfaceVariant: "#c9bab2",
      outline: "#a99b94",
      outlineVariant: "#8b7d76",
      border: "#362b25",
    },
  },
  rose: {
    name: "Rose",
    swatchLight: "#f7d4d9",
    swatchDark: "#870139",
    light: {
      surfaceContainer: "#fef6f7",
      surface: "#fceef0",
      surfaceContainerHigh: "#f8e6e9",
      primary: "#870139",
      onPrimary: "#ffffff",
      primaryHover: "#5a0024",
      onSurface: "#080203",
      onSurfaceVariant: "#3f252a",
      outline: "#5b3f44",
      outlineVariant: "#785a5f",
      border: "#d6b4b9",
    },
    dark: {
      surfaceContainer: "#170c0e",
      surface: "#1e1214",
      surfaceContainerHigh: "#2a1e20",
      primary: "#eba9b5",
      onPrimary: "#000000",
      primaryHover: "#dd7d92",
      onSurface: "#ebd9dc",
      onSurfaceVariant: "#d6b4b9",
      outline: "#b5959a",
      outlineVariant: "#96777c",
      border: "#3f252a",
    },
  },
  pink: {
    name: "Pink",
    swatchLight: "#f7d4d9",
    swatchDark: "#633a42",
    light: {
      surfaceContainer: "#fef6f7",
      surface: "#fceef0",
      surfaceContainerHigh: "#f5e7e9",
      primary: "#633a42",
      onPrimary: "#ffffff",
      primaryHover: "#462029",
      onSurface: "#060203",
      onSurfaceVariant: "#372a2c",
      outline: "#524346",
      outlineVariant: "#6e5f61",
      border: "#cab9bb",
    },
    dark: {
      surfaceContainer: "#150d0e",
      surface: "#1c1315",
      surfaceContainerHigh: "#281f20",
      primary: "#e1aeb7",
      onPrimary: "#000000",
      primaryHover: "#c08f98",
      onSurface: "#e8dadc",
      onSurfaceVariant: "#cab9bb",
      outline: "#aa9a9c",
      outlineVariant: "#8b7c7e",
      border: "#372a2c",
    },
  },
  fuchsia: {
    name: "Fuchsia",
    swatchLight: "#edd5ec",
    swatchDark: "#721871",
    light: {
      surfaceContainer: "#fcf7fb",
      surface: "#f8eef7",
      surfaceContainerHigh: "#f3e7f2",
      primary: "#721871",
      onPrimary: "#ffffff",
      primaryHover: "#4b0d4b",
      onSurface: "#060206",
      onSurfaceVariant: "#392738",
      outline: "#544053",
      outlineVariant: "#705b6f",
      border: "#cdb5cb",
    },
    dark: {
      surfaceContainer: "#140c14",
      surface: "#1b131b",
      surfaceContainerHigh: "#271e26",
      primary: "#dbacd8",
      onPrimary: "#000000",
      primaryHover: "#c783c4",
      onSurface: "#e6dae5",
      onSurfaceVariant: "#cdb5cb",
      outline: "#ad96ab",
      outlineVariant: "#8e788c",
      border: "#392738",
    },
  },
  violet: {
    name: "Violet",
    swatchLight: "#e3d8f4",
    swatchDark: "#5b268c",
    light: {
      surfaceContainer: "#f9f7fd",
      surface: "#f4effb",
      surfaceContainerHigh: "#eee8f6",
      primary: "#5b268c",
      onPrimary: "#ffffff",
      primaryHover: "#3c165d",
      onSurface: "#040208",
      onSurfaceVariant: "#32293e",
      outline: "#4c425a",
      outlineVariant: "#685e76",
      border: "#c3b8d3",
    },
    dark: {
      surfaceContainer: "#110d17",
      surface: "#18141e",
      surfaceContainerHigh: "#241f2a",
      primary: "#c9b1e8",
      onPrimary: "#000000",
      primaryHover: "#af8bdb",
      onSurface: "#e1dbe9",
      onSurfaceVariant: "#c3b8d3",
      outline: "#a499b3",
      outlineVariant: "#857b94",
      border: "#32293e",
    },
  },
};

export const defaultThemeId = "default";

const cssVarMap: Record<keyof ThemeColors, string> = {
  surfaceContainer: "--color-surface-container",
  surface: "--color-surface",
  surfaceContainerHigh: "--color-surface-container-high",
  primary: "--color-primary",
  onPrimary: "--color-on-primary",
  primaryHover: "--color-primary-hover",
  onSurface: "--color-on-surface",
  onSurfaceVariant: "--color-on-surface-variant",
  outline: "--color-outline",
  outlineVariant: "--color-outline-variant",
  border: "--color-border",
};

export function applyTheme(themeId: string): void {
  const preset = themePresets[themeId];
  if (!preset) return;

  const root = document.documentElement;
  for (const [key, cssVar] of Object.entries(cssVarMap)) {
    const light = preset.light[key as keyof ThemeColors];
    const dark = preset.dark[key as keyof ThemeColors];
    root.style.setProperty(cssVar, `light-dark(${light}, ${dark})`);
  }
}
